"""
Authentication utilities.
Supports both Supabase JWT and local JWT tokens.
"""
from fastapi import HTTPException, Request
from typing import Optional
import jwt
import uuid

from ..config import get_settings
from ..services.google_auth import google_auth


async def get_current_user_id(request: Request) -> str:
    """
    Dependency: Extract and verify user_id from the Authorization header.
    
    Supports:
    1. SKIP_AUTH mode (returns demo user)
    2. Local JWT tokens (generated by google_auth service)
    3. Supabase JWT tokens (legacy support)
    """
    settings = get_settings()
    
    # Skip auth mode for testing
    if settings.skip_auth:
        return "579fce1e-1604-4b00-b692-1f3b5ce43368"
    
    auth_header = request.headers.get("authorization", "")
    
    if not auth_header.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Missing or invalid authorization token")
    
    token = auth_header[7:]
    
    # Try local JWT first
    payload = google_auth.verify_jwt(token)
    if payload and payload.get("sub"):
        return payload["sub"]
    
    # Try Supabase JWT (legacy support)
    try:
        payload = jwt.decode(
            token,
            options={
                "verify_signature": False,
                "verify_exp": True,
                "verify_nbf": True,
                "verify_iat": True,
                "verify_iss": False,
            },
            algorithms=["HS256"],
        )
        user_id = payload.get("sub")
        if user_id:
            return user_id
    except jwt.ExpiredSignatureError:
        pass
    except jwt.InvalidTokenError:
        pass
    
    raise HTTPException(status_code=401, detail="Invalid or expired token")
