"""
Authentication utilities.
Verifies local JWT tokens (generated by the google_auth service).
"""
from fastapi import HTTPException, Request

from ..config import get_settings
from ..services.google_auth import google_auth


async def get_current_user_id(request: Request) -> str:
    """
    Dependency: Extract and verify user_id from the Authorization header.

    Supports:
    1. SKIP_AUTH mode (returns demo user, development only)
    2. Signed local JWT tokens (HS256, generated by google_auth service)

    Tokens that are not correctly signed with JWT_SECRET are rejected.
    """
    settings = get_settings()

    # Skip auth mode for testing
    if settings.skip_auth:
        return "579fce1e-1604-4b00-b692-1f3b5ce43368"

    auth_header = request.headers.get("authorization", "")

    if not auth_header.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Missing or invalid authorization token")

    token = auth_header[7:]

    payload = google_auth.verify_jwt(token)
    if payload and payload.get("sub"):
        return payload["sub"]

    raise HTTPException(status_code=401, detail="Invalid or expired token")
